// AirportDatabase.swift — static list of ~300 major airports worldwide
import Foundation

struct AirportRecord: Equatable, Sendable, Identifiable {
    var id: String { iata }
    let iata: String
    let icao: String
    let name: String
    let city: String
    let countryISO: String
    let lat: Double
    let lon: Double
}

// swiftlint:disable line_length
let kAirportDatabase: [AirportRecord] = [
    // North America
    AirportRecord(iata:"ATL",icao:"KATL",name:"Hartsfield–Jackson Atlanta International",city:"Atlanta",countryISO:"US",lat:33.6407,lon:-84.4277),
    AirportRecord(iata:"LAX",icao:"KLAX",name:"Los Angeles International",city:"Los Angeles",countryISO:"US",lat:33.9425,lon:-118.4081),
    AirportRecord(iata:"ORD",icao:"KORD",name:"O'Hare International",city:"Chicago",countryISO:"US",lat:41.9742,lon:-87.9073),
    AirportRecord(iata:"DFW",icao:"KDFW",name:"Dallas/Fort Worth International",city:"Dallas",countryISO:"US",lat:32.8998,lon:-97.0403),
    AirportRecord(iata:"DEN",icao:"KDEN",name:"Denver International",city:"Denver",countryISO:"US",lat:39.8561,lon:-104.6737),
    AirportRecord(iata:"JFK",icao:"KJFK",name:"John F. Kennedy International",city:"New York",countryISO:"US",lat:40.6413,lon:-73.7781),
    AirportRecord(iata:"SFO",icao:"KSFO",name:"San Francisco International",city:"San Francisco",countryISO:"US",lat:37.6213,lon:-122.3790),
    AirportRecord(iata:"SEA",icao:"KSEA",name:"Seattle–Tacoma International",city:"Seattle",countryISO:"US",lat:47.4502,lon:-122.3088),
    AirportRecord(iata:"LAS",icao:"KLAS",name:"Harry Reid International",city:"Las Vegas",countryISO:"US",lat:36.0840,lon:-115.1537),
    AirportRecord(iata:"MCO",icao:"KMCO",name:"Orlando International",city:"Orlando",countryISO:"US",lat:28.4294,lon:-81.3089),
    AirportRecord(iata:"EWR",icao:"KEWR",name:"Newark Liberty International",city:"Newark",countryISO:"US",lat:40.6895,lon:-74.1745),
    AirportRecord(iata:"MIA",icao:"KMIA",name:"Miami International",city:"Miami",countryISO:"US",lat:25.7959,lon:-80.2870),
    AirportRecord(iata:"PHX",icao:"KPHX",name:"Phoenix Sky Harbor International",city:"Phoenix",countryISO:"US",lat:33.4373,lon:-112.0078),
    AirportRecord(iata:"IAH",icao:"KIAH",name:"George Bush Intercontinental",city:"Houston",countryISO:"US",lat:29.9902,lon:-95.3368),
    AirportRecord(iata:"BOS",icao:"KBOS",name:"Boston Logan International",city:"Boston",countryISO:"US",lat:42.3656,lon:-71.0096),
    AirportRecord(iata:"MSP",icao:"KMSP",name:"Minneapolis–Saint Paul International",city:"Minneapolis",countryISO:"US",lat:44.8848,lon:-93.2223),
    AirportRecord(iata:"DTW",icao:"KDTW",name:"Detroit Metropolitan Wayne County",city:"Detroit",countryISO:"US",lat:42.2162,lon:-83.3554),
    AirportRecord(iata:"PHL",icao:"KPHL",name:"Philadelphia International",city:"Philadelphia",countryISO:"US",lat:39.8744,lon:-75.2424),
    AirportRecord(iata:"LGA",icao:"KLGA",name:"LaGuardia",city:"New York",countryISO:"US",lat:40.7772,lon:-73.8726),
    AirportRecord(iata:"BWI",icao:"KBWI",name:"Baltimore/Washington International",city:"Baltimore",countryISO:"US",lat:39.1754,lon:-76.6683),
    AirportRecord(iata:"IAD",icao:"KIAD",name:"Washington Dulles International",city:"Washington",countryISO:"US",lat:38.9531,lon:-77.4565),
    AirportRecord(iata:"DCA",icao:"KDCA",name:"Ronald Reagan Washington National",city:"Washington",countryISO:"US",lat:38.8521,lon:-77.0377),
    AirportRecord(iata:"SLC",icao:"KSLC",name:"Salt Lake City International",city:"Salt Lake City",countryISO:"US",lat:40.7884,lon:-111.9778),
    AirportRecord(iata:"SAN",icao:"KSAN",name:"San Diego International",city:"San Diego",countryISO:"US",lat:32.7336,lon:-117.1897),
    AirportRecord(iata:"TPA",icao:"KTPA",name:"Tampa International",city:"Tampa",countryISO:"US",lat:27.9755,lon:-82.5332),
    AirportRecord(iata:"PDX",icao:"KPDX",name:"Portland International",city:"Portland",countryISO:"US",lat:45.5887,lon:-122.5975),
    AirportRecord(iata:"HNL",icao:"PHNL",name:"Daniel K. Inouye International",city:"Honolulu",countryISO:"US",lat:21.3245,lon:-157.9251),
    AirportRecord(iata:"AUS",icao:"KAUS",name:"Austin-Bergstrom International",city:"Austin",countryISO:"US",lat:30.1975,lon:-97.6664),
    AirportRecord(iata:"BNA",icao:"KBNA",name:"Nashville International",city:"Nashville",countryISO:"US",lat:36.1245,lon:-86.6782),
    AirportRecord(iata:"CLT",icao:"KCLT",name:"Charlotte Douglas International",city:"Charlotte",countryISO:"US",lat:35.2140,lon:-80.9431),
    // Canada
    AirportRecord(iata:"YYZ",icao:"CYYZ",name:"Toronto Pearson International",city:"Toronto",countryISO:"CA",lat:43.6772,lon:-79.6306),
    AirportRecord(iata:"YVR",icao:"CYVR",name:"Vancouver International",city:"Vancouver",countryISO:"CA",lat:49.1967,lon:-123.1815),
    AirportRecord(iata:"YUL",icao:"CYUL",name:"Montréal–Trudeau International",city:"Montreal",countryISO:"CA",lat:45.4706,lon:-73.7408),
    AirportRecord(iata:"YYC",icao:"CYYC",name:"Calgary International",city:"Calgary",countryISO:"CA",lat:51.1315,lon:-114.0106),
    AirportRecord(iata:"YEG",icao:"CYEG",name:"Edmonton International",city:"Edmonton",countryISO:"CA",lat:53.3097,lon:-113.5792),
    AirportRecord(iata:"YOW",icao:"CYOW",name:"Ottawa Macdonald–Cartier International",city:"Ottawa",countryISO:"CA",lat:45.3225,lon:-75.6692),
    // Mexico
    AirportRecord(iata:"MEX",icao:"MMMX",name:"Mexico City International",city:"Mexico City",countryISO:"MX",lat:19.4363,lon:-99.0721),
    AirportRecord(iata:"CUN",icao:"MMUN",name:"Cancún International",city:"Cancún",countryISO:"MX",lat:21.0365,lon:-86.8771),
    AirportRecord(iata:"GDL",icao:"MMGL",name:"Miguel Hidalgo International",city:"Guadalajara",countryISO:"MX",lat:20.5218,lon:-103.3112),
    // Europe
    AirportRecord(iata:"LHR",icao:"EGLL",name:"Heathrow",city:"London",countryISO:"GB",lat:51.4775,lon:-0.4614),
    AirportRecord(iata:"LGW",icao:"EGKK",name:"Gatwick",city:"London",countryISO:"GB",lat:51.1537,lon:-0.1821),
    AirportRecord(iata:"STN",icao:"EGSS",name:"Stansted",city:"London",countryISO:"GB",lat:51.8850,lon:0.2350),
    AirportRecord(iata:"MAN",icao:"EGCC",name:"Manchester",city:"Manchester",countryISO:"GB",lat:53.3537,lon:-2.2750),
    AirportRecord(iata:"EDI",icao:"EGPH",name:"Edinburgh",city:"Edinburgh",countryISO:"GB",lat:55.9500,lon:-3.3725),
    AirportRecord(iata:"CDG",icao:"LFPG",name:"Charles de Gaulle",city:"Paris",countryISO:"FR",lat:49.0097,lon:2.5479),
    AirportRecord(iata:"ORY",icao:"LFPO",name:"Paris Orly",city:"Paris",countryISO:"FR",lat:48.7233,lon:2.3794),
    AirportRecord(iata:"NCE",icao:"LFMN",name:"Nice Côte d'Azur",city:"Nice",countryISO:"FR",lat:43.6584,lon:7.2159),
    AirportRecord(iata:"LYS",icao:"LFLL",name:"Lyon Saint-Exupéry",city:"Lyon",countryISO:"FR",lat:45.7256,lon:5.0811),
    AirportRecord(iata:"FRA",icao:"EDDF",name:"Frankfurt",city:"Frankfurt",countryISO:"DE",lat:50.0379,lon:8.5622),
    AirportRecord(iata:"MUC",icao:"EDDM",name:"Munich",city:"Munich",countryISO:"DE",lat:48.3538,lon:11.7861),
    AirportRecord(iata:"BER",icao:"EDDB",name:"Berlin Brandenburg",city:"Berlin",countryISO:"DE",lat:52.3667,lon:13.5033),
    AirportRecord(iata:"HAM",icao:"EDDH",name:"Hamburg",city:"Hamburg",countryISO:"DE",lat:53.6304,lon:9.9882),
    AirportRecord(iata:"DUS",icao:"EDDL",name:"Düsseldorf",city:"Düsseldorf",countryISO:"DE",lat:51.2895,lon:6.7668),
    AirportRecord(iata:"AMS",icao:"EHAM",name:"Amsterdam Schiphol",city:"Amsterdam",countryISO:"NL",lat:52.3086,lon:4.7639),
    AirportRecord(iata:"MAD",icao:"LEMD",name:"Adolfo Suárez Madrid–Barajas",city:"Madrid",countryISO:"ES",lat:40.4936,lon:-3.5668),
    AirportRecord(iata:"BCN",icao:"LEBL",name:"Barcelona–El Prat",city:"Barcelona",countryISO:"ES",lat:41.2971,lon:2.0785),
    AirportRecord(iata:"AGP",icao:"LEMG",name:"Málaga–Costa del Sol",city:"Málaga",countryISO:"ES",lat:36.6749,lon:-4.4991),
    AirportRecord(iata:"PMI",icao:"LEPA",name:"Palma de Mallorca",city:"Palma",countryISO:"ES",lat:39.5517,lon:2.7388),
    AirportRecord(iata:"FCO",icao:"LIRF",name:"Leonardo da Vinci–Fiumicino",city:"Rome",countryISO:"IT",lat:41.8003,lon:12.2389),
    AirportRecord(iata:"MXP",icao:"LIMC",name:"Milan Malpensa",city:"Milan",countryISO:"IT",lat:45.6306,lon:8.7281),
    AirportRecord(iata:"VCE",icao:"LIPZ",name:"Venice Marco Polo",city:"Venice",countryISO:"IT",lat:45.5053,lon:12.3519),
    AirportRecord(iata:"NAP",icao:"LIRN",name:"Naples International",city:"Naples",countryISO:"IT",lat:40.8860,lon:14.2908),
    AirportRecord(iata:"ATH",icao:"LGAV",name:"Athens International Eleftherios Venizelos",city:"Athens",countryISO:"GR",lat:37.9364,lon:23.9445),
    AirportRecord(iata:"SKG",icao:"LGTS",name:"Thessaloniki International Makedonia",city:"Thessaloniki",countryISO:"GR",lat:40.5197,lon:22.9709),
    AirportRecord(iata:"ZRH",icao:"LSZH",name:"Zurich",city:"Zurich",countryISO:"CH",lat:47.4647,lon:8.5492),
    AirportRecord(iata:"GVA",icao:"LSGG",name:"Geneva",city:"Geneva",countryISO:"CH",lat:46.2380,lon:6.1089),
    AirportRecord(iata:"VIE",icao:"LOWW",name:"Vienna International",city:"Vienna",countryISO:"AT",lat:48.1103,lon:16.5697),
    AirportRecord(iata:"BRU",icao:"EBBR",name:"Brussels",city:"Brussels",countryISO:"BE",lat:50.9014,lon:4.4844),
    AirportRecord(iata:"CPH",icao:"EKCH",name:"Copenhagen",city:"Copenhagen",countryISO:"DK",lat:55.6180,lon:12.6560),
    AirportRecord(iata:"OSL",icao:"ENGM",name:"Oslo Gardermoen",city:"Oslo",countryISO:"NO",lat:60.1939,lon:11.1004),
    AirportRecord(iata:"ARN",icao:"ESSA",name:"Stockholm Arlanda",city:"Stockholm",countryISO:"SE",lat:59.6519,lon:17.9186),
    AirportRecord(iata:"HEL",icao:"EFHK",name:"Helsinki Vantaa",city:"Helsinki",countryISO:"FI",lat:60.3172,lon:24.9633),
    AirportRecord(iata:"LIS",icao:"LPPT",name:"Lisbon Humberto Delgado",city:"Lisbon",countryISO:"PT",lat:38.7813,lon:-9.1359),
    AirportRecord(iata:"OPO",icao:"LPPR",name:"Francisco de Sá Carneiro",city:"Porto",countryISO:"PT",lat:41.2481,lon:-8.6814),
    AirportRecord(iata:"DUB",icao:"EIDW",name:"Dublin",city:"Dublin",countryISO:"IE",lat:53.4213,lon:-6.2701),
    AirportRecord(iata:"WAW",icao:"EPWA",name:"Warsaw Chopin",city:"Warsaw",countryISO:"PL",lat:52.1657,lon:20.9671),
    AirportRecord(iata:"PRG",icao:"LKPR",name:"Václav Havel Prague",city:"Prague",countryISO:"CZ",lat:50.1008,lon:14.2600),
    AirportRecord(iata:"BUD",icao:"LHBP",name:"Budapest Ferenc Liszt",city:"Budapest",countryISO:"HU",lat:47.4298,lon:19.2611),
    AirportRecord(iata:"OTP",icao:"LROP",name:"Henri Coandă International",city:"Bucharest",countryISO:"RO",lat:44.5711,lon:26.0858),
    AirportRecord(iata:"SOF",icao:"LBSF",name:"Sofia",city:"Sofia",countryISO:"BG",lat:42.6952,lon:23.4114),
    AirportRecord(iata:"IST",icao:"LTFM",name:"Istanbul",city:"Istanbul",countryISO:"TR",lat:41.2753,lon:28.7519),
    AirportRecord(iata:"SAW",icao:"LTFJ",name:"Istanbul Sabiha Gökçen",city:"Istanbul",countryISO:"TR",lat:40.8986,lon:29.3092),
    AirportRecord(iata:"AYT",icao:"LTAI",name:"Antalya",city:"Antalya",countryISO:"TR",lat:36.8987,lon:30.8005),
    AirportRecord(iata:"KBP",icao:"UKBB",name:"Kyiv Boryspil",city:"Kyiv",countryISO:"UA",lat:50.3450,lon:30.8947),
    AirportRecord(iata:"SVO",icao:"UUEE",name:"Sheremetyevo",city:"Moscow",countryISO:"RU",lat:55.9726,lon:37.4146),
    AirportRecord(iata:"DME",icao:"UUDD",name:"Domodedovo",city:"Moscow",countryISO:"RU",lat:55.4088,lon:37.9063),
    AirportRecord(iata:"LED",icao:"ULLI",name:"Pulkovo",city:"St. Petersburg",countryISO:"RU",lat:59.8003,lon:30.2625),
    AirportRecord(iata:"HRG",icao:"HEGN",name:"Hurghada International",city:"Hurghada",countryISO:"EG",lat:27.1783,lon:33.7994),
    AirportRecord(iata:"SSH",icao:"HESH",name:"Sharm el-Sheikh International",city:"Sharm el-Sheikh",countryISO:"EG",lat:27.9773,lon:34.3950),
    AirportRecord(iata:"RIX",icao:"EVRA",name:"Riga International",city:"Riga",countryISO:"LV",lat:56.9236,lon:23.9711),
    AirportRecord(iata:"TLL",icao:"EETN",name:"Tallinn",city:"Tallinn",countryISO:"EE",lat:59.4133,lon:24.8328),
    AirportRecord(iata:"VNO",icao:"EYVI",name:"Vilnius",city:"Vilnius",countryISO:"LT",lat:54.6341,lon:25.2858),
    AirportRecord(iata:"LJU",icao:"LJLJ",name:"Ljubljana Jože Pučnik",city:"Ljubljana",countryISO:"SI",lat:46.2237,lon:14.4576),
    AirportRecord(iata:"ZAG",icao:"LDZA",name:"Zagreb",city:"Zagreb",countryISO:"HR",lat:45.7429,lon:16.0688),
    AirportRecord(iata:"SPU",icao:"LDSP",name:"Split",city:"Split",countryISO:"HR",lat:43.5389,lon:16.2980),
    AirportRecord(iata:"DBV",icao:"LDDU",name:"Dubrovnik",city:"Dubrovnik",countryISO:"HR",lat:42.5614,lon:18.2682),
    AirportRecord(iata:"BEG",icao:"LYBE",name:"Belgrade Nikola Tesla",city:"Belgrade",countryISO:"RS",lat:44.8184,lon:20.3091),
    AirportRecord(iata:"SKP",icao:"LWSK",name:"Skopje Alexander the Great",city:"Skopje",countryISO:"MK",lat:41.9616,lon:21.6214),
    AirportRecord(iata:"TIA",icao:"LATI",name:"Tirana International Nënë Tereza",city:"Tirana",countryISO:"AL",lat:41.4147,lon:19.7206),
    AirportRecord(iata:"OHD",icao:"LWOH",name:"Ohrid St. Paul the Apostle",city:"Ohrid",countryISO:"MK",lat:41.1800,lon:20.7423),
    // Middle East
    AirportRecord(iata:"DXB",icao:"OMDB",name:"Dubai International",city:"Dubai",countryISO:"AE",lat:25.2532,lon:55.3657),
    AirportRecord(iata:"AUH",icao:"OMAA",name:"Abu Dhabi International",city:"Abu Dhabi",countryISO:"AE",lat:24.4330,lon:54.6511),
    AirportRecord(iata:"DOH",icao:"OTHH",name:"Hamad International",city:"Doha",countryISO:"QA",lat:25.2731,lon:51.6081),
    AirportRecord(iata:"KWI",icao:"OKBK",name:"Kuwait International",city:"Kuwait City",countryISO:"KW",lat:29.2267,lon:47.9689),
    AirportRecord(iata:"BAH",icao:"OBBI",name:"Bahrain International",city:"Manama",countryISO:"BH",lat:26.2708,lon:50.6336),
    AirportRecord(iata:"MCT",icao:"OOMS",name:"Muscat International",city:"Muscat",countryISO:"OM",lat:23.5933,lon:58.2844),
    AirportRecord(iata:"AMM",icao:"OJAI",name:"Queen Alia International",city:"Amman",countryISO:"JO",lat:31.7226,lon:35.9932),
    AirportRecord(iata:"BEY",icao:"OLBA",name:"Rafic Hariri International",city:"Beirut",countryISO:"LB",lat:33.8209,lon:35.4884),
    AirportRecord(iata:"TLV",icao:"LLBG",name:"Ben Gurion International",city:"Tel Aviv",countryISO:"IL",lat:32.0114,lon:34.8867),
    AirportRecord(iata:"RUH",icao:"OERK",name:"King Khalid International",city:"Riyadh",countryISO:"SA",lat:24.9576,lon:46.6988),
    AirportRecord(iata:"JED",icao:"OEJN",name:"King Abdulaziz International",city:"Jeddah",countryISO:"SA",lat:21.6796,lon:39.1565),
    AirportRecord(iata:"IKA",icao:"OIIE",name:"Imam Khomeini International",city:"Tehran",countryISO:"IR",lat:35.4161,lon:51.1522),
    // Asia Pacific
    AirportRecord(iata:"PEK",icao:"ZBAA",name:"Beijing Capital International",city:"Beijing",countryISO:"CN",lat:40.0799,lon:116.6031),
    AirportRecord(iata:"PKX",icao:"ZBAD",name:"Beijing Daxing International",city:"Beijing",countryISO:"CN",lat:39.5098,lon:116.4105),
    AirportRecord(iata:"PVG",icao:"ZSPD",name:"Shanghai Pudong International",city:"Shanghai",countryISO:"CN",lat:31.1434,lon:121.8052),
    AirportRecord(iata:"SHA",icao:"ZSSS",name:"Shanghai Hongqiao International",city:"Shanghai",countryISO:"CN",lat:31.1979,lon:121.3362),
    AirportRecord(iata:"CAN",icao:"ZGGG",name:"Guangzhou Baiyun International",city:"Guangzhou",countryISO:"CN",lat:23.3924,lon:113.2988),
    AirportRecord(iata:"CTU",icao:"ZUUU",name:"Chengdu Tianfu International",city:"Chengdu",countryISO:"CN",lat:30.3124,lon:104.4441),
    AirportRecord(iata:"SZX",icao:"ZGSZ",name:"Shenzhen Bao'an International",city:"Shenzhen",countryISO:"CN",lat:22.6393,lon:113.8108),
    AirportRecord(iata:"HKG",icao:"VHHH",name:"Hong Kong International",city:"Hong Kong",countryISO:"HK",lat:22.3080,lon:113.9185),
    AirportRecord(iata:"TPE",icao:"RCTP",name:"Taiwan Taoyuan International",city:"Taipei",countryISO:"TW",lat:25.0777,lon:121.2328),
    AirportRecord(iata:"ICN",icao:"RKSI",name:"Incheon International",city:"Seoul",countryISO:"KR",lat:37.4691,lon:126.4505),
    AirportRecord(iata:"GMP",icao:"RKSS",name:"Gimpo International",city:"Seoul",countryISO:"KR",lat:37.5583,lon:126.7906),
    AirportRecord(iata:"NRT",icao:"RJAA",name:"Narita International",city:"Tokyo",countryISO:"JP",lat:35.7720,lon:140.3929),
    AirportRecord(iata:"HND",icao:"RJTT",name:"Tokyo Haneda",city:"Tokyo",countryISO:"JP",lat:35.5494,lon:139.7798),
    AirportRecord(iata:"KIX",icao:"RJBB",name:"Kansai International",city:"Osaka",countryISO:"JP",lat:34.4347,lon:135.2440),
    AirportRecord(iata:"NGO",icao:"RJGG",name:"Chubu Centrair International",city:"Nagoya",countryISO:"JP",lat:34.8584,lon:136.8054),
    AirportRecord(iata:"BKK",icao:"VTBS",name:"Suvarnabhumi",city:"Bangkok",countryISO:"TH",lat:13.6900,lon:100.7501),
    AirportRecord(iata:"DMK",icao:"VTBD",name:"Don Mueang International",city:"Bangkok",countryISO:"TH",lat:13.9126,lon:100.6067),
    AirportRecord(iata:"HKT",icao:"VTSP",name:"Phuket International",city:"Phuket",countryISO:"TH",lat:8.1132,lon:98.3169),
    AirportRecord(iata:"CNX",icao:"VTCC",name:"Chiang Mai International",city:"Chiang Mai",countryISO:"TH",lat:18.7668,lon:98.9628),
    AirportRecord(iata:"SIN",icao:"WSSS",name:"Singapore Changi",city:"Singapore",countryISO:"SG",lat:1.3644,lon:103.9915),
    AirportRecord(iata:"KUL",icao:"WMKK",name:"Kuala Lumpur International",city:"Kuala Lumpur",countryISO:"MY",lat:2.7456,lon:101.7099),
    AirportRecord(iata:"CGK",icao:"WIII",name:"Soekarno–Hatta International",city:"Jakarta",countryISO:"ID",lat:-6.1256,lon:106.6559),
    AirportRecord(iata:"DPS",icao:"WADD",name:"Ngurah Rai International",city:"Bali",countryISO:"ID",lat:-8.7482,lon:115.1670),
    AirportRecord(iata:"MNL",icao:"RPLL",name:"Ninoy Aquino International",city:"Manila",countryISO:"PH",lat:14.5086,lon:121.0197),
    AirportRecord(iata:"CEB",icao:"RPVM",name:"Mactan–Cebu International",city:"Cebu",countryISO:"PH",lat:10.3075,lon:123.9792),
    AirportRecord(iata:"SGN",icao:"VVTS",name:"Tan Son Nhat International",city:"Ho Chi Minh City",countryISO:"VN",lat:10.8188,lon:106.6520),
    AirportRecord(iata:"HAN",icao:"VVNB",name:"Noi Bai International",city:"Hanoi",countryISO:"VN",lat:21.2212,lon:105.8072),
    AirportRecord(iata:"DAD",icao:"VVDN",name:"Da Nang International",city:"Da Nang",countryISO:"VN",lat:16.0439,lon:108.1993),
    AirportRecord(iata:"REP",icao:"VDSR",name:"Siem Reap–Angkor International",city:"Siem Reap",countryISO:"KH",lat:13.3507,lon:103.8097),
    AirportRecord(iata:"PNH",icao:"VDPP",name:"Phnom Penh International",city:"Phnom Penh",countryISO:"KH",lat:11.5466,lon:104.8441),
    AirportRecord(iata:"RGN",icao:"VYYY",name:"Yangon International",city:"Yangon",countryISO:"MM",lat:16.9073,lon:96.1332),
    AirportRecord(iata:"DEL",icao:"VIDP",name:"Indira Gandhi International",city:"New Delhi",countryISO:"IN",lat:28.5562,lon:77.1000),
    AirportRecord(iata:"BOM",icao:"VABB",name:"Chhatrapati Shivaji Maharaj International",city:"Mumbai",countryISO:"IN",lat:19.0896,lon:72.8656),
    AirportRecord(iata:"BLR",icao:"VOBL",name:"Kempegowda International",city:"Bangalore",countryISO:"IN",lat:13.1986,lon:77.7066),
    AirportRecord(iata:"MAA",icao:"VOMM",name:"Chennai International",city:"Chennai",countryISO:"IN",lat:12.9900,lon:80.1693),
    AirportRecord(iata:"HYD",icao:"VOHS",name:"Rajiv Gandhi International",city:"Hyderabad",countryISO:"IN",lat:17.2313,lon:78.4298),
    AirportRecord(iata:"CCU",icao:"VECC",name:"Netaji Subhas Chandra Bose International",city:"Kolkata",countryISO:"IN",lat:22.6520,lon:88.4463),
    AirportRecord(iata:"CMB",icao:"VCBI",name:"Bandaranaike International",city:"Colombo",countryISO:"LK",lat:7.1808,lon:79.8841),
    AirportRecord(iata:"DAC",icao:"VGHS",name:"Hazrat Shahjalal International",city:"Dhaka",countryISO:"BD",lat:23.8433,lon:90.3978),
    AirportRecord(iata:"KTM",icao:"VNKT",name:"Tribhuvan International",city:"Kathmandu",countryISO:"NP",lat:27.6966,lon:85.3591),
    AirportRecord(iata:"KHI",icao:"OPKC",name:"Jinnah International",city:"Karachi",countryISO:"PK",lat:24.9065,lon:67.1608),
    AirportRecord(iata:"LHE",icao:"OPLA",name:"Allama Iqbal International",city:"Lahore",countryISO:"PK",lat:31.5216,lon:74.4036),
    AirportRecord(iata:"ISB",icao:"OPIS",name:"Islamabad International",city:"Islamabad",countryISO:"PK",lat:33.5607,lon:72.8516),
    AirportRecord(iata:"ULN",icao:"ZMUB",name:"Chinggis Khaan International",city:"Ulaanbaatar",countryISO:"MN",lat:47.8431,lon:106.7664),
    AirportRecord(iata:"TAS",icao:"UTTT",name:"Tashkent International",city:"Tashkent",countryISO:"UZ",lat:41.2579,lon:69.2812),
    AirportRecord(iata:"ALA",icao:"UAAA",name:"Almaty International",city:"Almaty",countryISO:"KZ",lat:43.3521,lon:77.0405),
    // Oceania
    AirportRecord(iata:"SYD",icao:"YSSY",name:"Sydney Kingsford Smith",city:"Sydney",countryISO:"AU",lat:-33.9399,lon:151.1753),
    AirportRecord(iata:"MEL",icao:"YMML",name:"Melbourne",city:"Melbourne",countryISO:"AU",lat:-37.6690,lon:144.8410),
    AirportRecord(iata:"BNE",icao:"YBBN",name:"Brisbane",city:"Brisbane",countryISO:"AU",lat:-27.3842,lon:153.1175),
    AirportRecord(iata:"PER",icao:"YPPH",name:"Perth",city:"Perth",countryISO:"AU",lat:-31.9403,lon:115.9669),
    AirportRecord(iata:"ADL",icao:"YPAD",name:"Adelaide",city:"Adelaide",countryISO:"AU",lat:-34.9450,lon:138.5306),
    AirportRecord(iata:"AKL",icao:"NZAA",name:"Auckland",city:"Auckland",countryISO:"NZ",lat:-37.0082,lon:174.7917),
    AirportRecord(iata:"CHC",icao:"NZCH",name:"Christchurch",city:"Christchurch",countryISO:"NZ",lat:-43.4894,lon:172.5322),
    AirportRecord(iata:"WLG",icao:"NZWN",name:"Wellington",city:"Wellington",countryISO:"NZ",lat:-41.3272,lon:174.8051),
    AirportRecord(iata:"NAN",icao:"NFFN",name:"Nadi International",city:"Nadi",countryISO:"FJ",lat:-17.7554,lon:177.4430),
    // Africa
    AirportRecord(iata:"CAI",icao:"HECA",name:"Cairo International",city:"Cairo",countryISO:"EG",lat:30.1219,lon:31.4056),
    AirportRecord(iata:"JNB",icao:"FAOR",name:"O. R. Tambo International",city:"Johannesburg",countryISO:"ZA",lat:-26.1392,lon:28.2460),
    AirportRecord(iata:"CPT",icao:"FACT",name:"Cape Town International",city:"Cape Town",countryISO:"ZA",lat:-33.9649,lon:18.6017),
    AirportRecord(iata:"NBO",icao:"HKJK",name:"Jomo Kenyatta International",city:"Nairobi",countryISO:"KE",lat:-1.3192,lon:36.9275),
    AirportRecord(iata:"ADD",icao:"HAAB",name:"Addis Ababa Bole International",city:"Addis Ababa",countryISO:"ET",lat:8.9779,lon:38.7993),
    AirportRecord(iata:"LOS",icao:"DNMM",name:"Murtala Muhammed International",city:"Lagos",countryISO:"NG",lat:6.5774,lon:3.3212),
    AirportRecord(iata:"ABJ",icao:"DIAP",name:"Félix Houphouët-Boigny International",city:"Abidjan",countryISO:"CI",lat:5.2613,lon:-3.9263),
    AirportRecord(iata:"ACC",icao:"DGAA",name:"Kotoka International",city:"Accra",countryISO:"GH",lat:5.6052,lon:-0.1668),
    AirportRecord(iata:"CMN",icao:"GMMN",name:"Mohammed V International",city:"Casablanca",countryISO:"MA",lat:33.3675,lon:-7.5899),
    AirportRecord(iata:"RAK",icao:"GMMX",name:"Marrakesh Menara",city:"Marrakesh",countryISO:"MA",lat:31.6069,lon:-8.0363),
    AirportRecord(iata:"TUN",icao:"DTTA",name:"Tunis-Carthage International",city:"Tunis",countryISO:"TN",lat:36.8510,lon:10.2272),
    AirportRecord(iata:"ALG",icao:"DAAG",name:"Houari Boumediene",city:"Algiers",countryISO:"DZ",lat:36.6910,lon:3.2154),
    AirportRecord(iata:"DAR",icao:"HTDA",name:"Julius Nyerere International",city:"Dar es Salaam",countryISO:"TZ",lat:-6.8781,lon:39.2026),
    AirportRecord(iata:"EBB",icao:"HUEN",name:"Entebbe International",city:"Kampala",countryISO:"UG",lat:0.0424,lon:32.4435),
    AirportRecord(iata:"KGL",icao:"HRYR",name:"Kigali International",city:"Kigali",countryISO:"RW",lat:-1.9686,lon:30.1395),
    AirportRecord(iata:"MPM",icao:"FQMA",name:"Maputo International",city:"Maputo",countryISO:"MZ",lat:-25.9208,lon:32.5726),
    AirportRecord(iata:"TNR",icao:"FMMI",name:"Ivato International",city:"Antananarivo",countryISO:"MG",lat:-18.7969,lon:47.4788),
    AirportRecord(iata:"DKR",icao:"GOBD",name:"Blaise Diagne International",city:"Dakar",countryISO:"SN",lat:14.6702,lon:-17.0726),
    AirportRecord(iata:"LFW",icao:"DXXX",name:"Lomé-Tokoin International",city:"Lomé",countryISO:"TG",lat:6.1661,lon:1.2545),
    // South America
    AirportRecord(iata:"GRU",icao:"SBGR",name:"São Paulo–Guarulhos International",city:"São Paulo",countryISO:"BR",lat:-23.4356,lon:-46.4731),
    AirportRecord(iata:"GIG",icao:"SBGL",name:"Rio de Janeiro–Galeão International",city:"Rio de Janeiro",countryISO:"BR",lat:-22.8099,lon:-43.2505),
    AirportRecord(iata:"BSB",icao:"SBBR",name:"Brasília International",city:"Brasília",countryISO:"BR",lat:-15.8711,lon:-47.9186),
    AirportRecord(iata:"SSA",icao:"SBSV",name:"Deputado Luís Eduardo Magalhães International",city:"Salvador",countryISO:"BR",lat:-12.9086,lon:-38.3225),
    AirportRecord(iata:"EZE",icao:"SAEZ",name:"Ministro Pistarini International",city:"Buenos Aires",countryISO:"AR",lat:-34.8222,lon:-58.5358),
    AirportRecord(iata:"AEP",icao:"SABE",name:"Jorge Newbery Airfield",city:"Buenos Aires",countryISO:"AR",lat:-34.5592,lon:-58.4156),
    AirportRecord(iata:"SCL",icao:"SCEL",name:"Arturo Merino Benítez International",city:"Santiago",countryISO:"CL",lat:-33.3930,lon:-70.7858),
    AirportRecord(iata:"LIM",icao:"SPIM",name:"Jorge Chávez International",city:"Lima",countryISO:"PE",lat:-12.0219,lon:-77.1143),
    AirportRecord(iata:"BOG",icao:"SKBO",name:"El Dorado International",city:"Bogotá",countryISO:"CO",lat:4.7016,lon:-74.1469),
    AirportRecord(iata:"MDE",icao:"SKRG",name:"José María Córdova International",city:"Medellín",countryISO:"CO",lat:6.1645,lon:-75.4231),
    AirportRecord(iata:"UIO",icao:"SEQM",name:"Mariscal Sucre International",city:"Quito",countryISO:"EC",lat:-0.1292,lon:-78.3575),
    AirportRecord(iata:"GYE",icao:"SEGU",name:"José Joaquín de Olmedo International",city:"Guayaquil",countryISO:"EC",lat:-2.1574,lon:-79.8836),
    AirportRecord(iata:"VVI",icao:"SLVR",name:"Viru Viru International",city:"Santa Cruz",countryISO:"BO",lat:-17.6448,lon:-63.1354),
    AirportRecord(iata:"ASU",icao:"SGAS",name:"Silvio Pettirossi International",city:"Asunción",countryISO:"PY",lat:-25.2400,lon:-57.5198),
    AirportRecord(iata:"MVD",icao:"SUMU",name:"Carrasco International",city:"Montevideo",countryISO:"UY",lat:-34.8384,lon:-56.0308),
    AirportRecord(iata:"CCS",icao:"SVMI",name:"Simón Bolívar International",city:"Caracas",countryISO:"VE",lat:10.6031,lon:-66.9912),
    AirportRecord(iata:"PTY",icao:"MPTO",name:"Tocumen International",city:"Panama City",countryISO:"PA",lat:9.0714,lon:-79.3835),
    AirportRecord(iata:"SJO",icao:"MROC",name:"Juan Santamaría International",city:"San José",countryISO:"CR",lat:9.9939,lon:-84.2088),
    AirportRecord(iata:"GUA",icao:"MGGT",name:"La Aurora International",city:"Guatemala City",countryISO:"GT",lat:14.5833,lon:-90.5275),
    AirportRecord(iata:"SAL",icao:"MSLP",name:"Monseñor Óscar Arnulfo Romero International",city:"San Salvador",countryISO:"SV",lat:13.4409,lon:-89.0557),
    AirportRecord(iata:"HAV",icao:"MUHA",name:"José Martí International",city:"Havana",countryISO:"CU",lat:22.9892,lon:-82.4091),
    AirportRecord(iata:"SJU",icao:"TJSJ",name:"Luis Muñoz Marín International",city:"San Juan",countryISO:"PR",lat:18.4394,lon:-66.0018),
    AirportRecord(iata:"SDQ",icao:"MDSD",name:"Las Américas International",city:"Santo Domingo",countryISO:"DO",lat:18.4297,lon:-69.6689),
    AirportRecord(iata:"MBJ",icao:"MKJS",name:"Sangster International",city:"Montego Bay",countryISO:"JM",lat:18.5037,lon:-77.9134),
]
// swiftlint:enable line_length
