//
//  CountryData.swift
//  Terris
//

import Foundation

struct CountryEntry {
    let name: String
    let isoCode: String
    let continent: String
}

struct CountryData {
    static let all: [CountryEntry] = [
        // Africa
        CountryEntry(name: "Algeria", isoCode: "DZ", continent: "Africa"),
        CountryEntry(name: "Angola", isoCode: "AO", continent: "Africa"),
        CountryEntry(name: "Benin", isoCode: "BJ", continent: "Africa"),
        CountryEntry(name: "Botswana", isoCode: "BW", continent: "Africa"),
        CountryEntry(name: "Burkina Faso", isoCode: "BF", continent: "Africa"),
        CountryEntry(name: "Burundi", isoCode: "BI", continent: "Africa"),
        CountryEntry(name: "Cameroon", isoCode: "CM", continent: "Africa"),
        CountryEntry(name: "Cape Verde", isoCode: "CV", continent: "Africa"),
        CountryEntry(name: "Central African Republic", isoCode: "CF", continent: "Africa"),
        CountryEntry(name: "Chad", isoCode: "TD", continent: "Africa"),
        CountryEntry(name: "Comoros", isoCode: "KM", continent: "Africa"),
        CountryEntry(name: "Congo", isoCode: "CG", continent: "Africa"),
        CountryEntry(name: "DR Congo", isoCode: "CD", continent: "Africa"),
        CountryEntry(name: "Djibouti", isoCode: "DJ", continent: "Africa"),
        CountryEntry(name: "Egypt", isoCode: "EG", continent: "Africa"),
        CountryEntry(name: "Equatorial Guinea", isoCode: "GQ", continent: "Africa"),
        CountryEntry(name: "Eritrea", isoCode: "ER", continent: "Africa"),
        CountryEntry(name: "Eswatini", isoCode: "SZ", continent: "Africa"),
        CountryEntry(name: "Ethiopia", isoCode: "ET", continent: "Africa"),
        CountryEntry(name: "Gabon", isoCode: "GA", continent: "Africa"),
        CountryEntry(name: "Gambia", isoCode: "GM", continent: "Africa"),
        CountryEntry(name: "Ghana", isoCode: "GH", continent: "Africa"),
        CountryEntry(name: "Guinea", isoCode: "GN", continent: "Africa"),
        CountryEntry(name: "Guinea-Bissau", isoCode: "GW", continent: "Africa"),
        CountryEntry(name: "Ivory Coast", isoCode: "CI", continent: "Africa"),
        CountryEntry(name: "Kenya", isoCode: "KE", continent: "Africa"),
        CountryEntry(name: "Lesotho", isoCode: "LS", continent: "Africa"),
        CountryEntry(name: "Liberia", isoCode: "LR", continent: "Africa"),
        CountryEntry(name: "Libya", isoCode: "LY", continent: "Africa"),
        CountryEntry(name: "Madagascar", isoCode: "MG", continent: "Africa"),
        CountryEntry(name: "Malawi", isoCode: "MW", continent: "Africa"),
        CountryEntry(name: "Mali", isoCode: "ML", continent: "Africa"),
        CountryEntry(name: "Mauritania", isoCode: "MR", continent: "Africa"),
        CountryEntry(name: "Mauritius", isoCode: "MU", continent: "Africa"),
        CountryEntry(name: "Morocco", isoCode: "MA", continent: "Africa"),
        CountryEntry(name: "Mozambique", isoCode: "MZ", continent: "Africa"),
        CountryEntry(name: "Namibia", isoCode: "NA", continent: "Africa"),
        CountryEntry(name: "Niger", isoCode: "NE", continent: "Africa"),
        CountryEntry(name: "Nigeria", isoCode: "NG", continent: "Africa"),
        CountryEntry(name: "Rwanda", isoCode: "RW", continent: "Africa"),
        CountryEntry(name: "São Tomé and Príncipe", isoCode: "ST", continent: "Africa"),
        CountryEntry(name: "Senegal", isoCode: "SN", continent: "Africa"),
        CountryEntry(name: "Seychelles", isoCode: "SC", continent: "Africa"),
        CountryEntry(name: "Sierra Leone", isoCode: "SL", continent: "Africa"),
        CountryEntry(name: "Somalia", isoCode: "SO", continent: "Africa"),
        CountryEntry(name: "South Africa", isoCode: "ZA", continent: "Africa"),
        CountryEntry(name: "South Sudan", isoCode: "SS", continent: "Africa"),
        CountryEntry(name: "Sudan", isoCode: "SD", continent: "Africa"),
        CountryEntry(name: "Tanzania", isoCode: "TZ", continent: "Africa"),
        CountryEntry(name: "Togo", isoCode: "TG", continent: "Africa"),
        CountryEntry(name: "Tunisia", isoCode: "TN", continent: "Africa"),
        CountryEntry(name: "Uganda", isoCode: "UG", continent: "Africa"),
        CountryEntry(name: "Zambia", isoCode: "ZM", continent: "Africa"),
        CountryEntry(name: "Zimbabwe", isoCode: "ZW", continent: "Africa"),
        // Asia
        CountryEntry(name: "Afghanistan", isoCode: "AF", continent: "Asia"),
        CountryEntry(name: "Armenia", isoCode: "AM", continent: "Asia"),
        CountryEntry(name: "Azerbaijan", isoCode: "AZ", continent: "Asia"),
        CountryEntry(name: "Bahrain", isoCode: "BH", continent: "Asia"),
        CountryEntry(name: "Bangladesh", isoCode: "BD", continent: "Asia"),
        CountryEntry(name: "Bhutan", isoCode: "BT", continent: "Asia"),
        CountryEntry(name: "Brunei", isoCode: "BN", continent: "Asia"),
        CountryEntry(name: "Cambodia", isoCode: "KH", continent: "Asia"),
        CountryEntry(name: "China", isoCode: "CN", continent: "Asia"),
        CountryEntry(name: "Cyprus", isoCode: "CY", continent: "Asia"),
        CountryEntry(name: "Georgia", isoCode: "GE", continent: "Asia"),
        CountryEntry(name: "India", isoCode: "IN", continent: "Asia"),
        CountryEntry(name: "Indonesia", isoCode: "ID", continent: "Asia"),
        CountryEntry(name: "Iran", isoCode: "IR", continent: "Asia"),
        CountryEntry(name: "Iraq", isoCode: "IQ", continent: "Asia"),
        CountryEntry(name: "Israel", isoCode: "IL", continent: "Asia"),
        CountryEntry(name: "Japan", isoCode: "JP", continent: "Asia"),
        CountryEntry(name: "Jordan", isoCode: "JO", continent: "Asia"),
        CountryEntry(name: "Kazakhstan", isoCode: "KZ", continent: "Asia"),
        CountryEntry(name: "Kuwait", isoCode: "KW", continent: "Asia"),
        CountryEntry(name: "Kyrgyzstan", isoCode: "KG", continent: "Asia"),
        CountryEntry(name: "Laos", isoCode: "LA", continent: "Asia"),
        CountryEntry(name: "Lebanon", isoCode: "LB", continent: "Asia"),
        CountryEntry(name: "Malaysia", isoCode: "MY", continent: "Asia"),
        CountryEntry(name: "Maldives", isoCode: "MV", continent: "Asia"),
        CountryEntry(name: "Mongolia", isoCode: "MN", continent: "Asia"),
        CountryEntry(name: "Myanmar", isoCode: "MM", continent: "Asia"),
        CountryEntry(name: "Nepal", isoCode: "NP", continent: "Asia"),
        CountryEntry(name: "North Korea", isoCode: "KP", continent: "Asia"),
        CountryEntry(name: "Oman", isoCode: "OM", continent: "Asia"),
        CountryEntry(name: "Pakistan", isoCode: "PK", continent: "Asia"),
        CountryEntry(name: "Palestine", isoCode: "PS", continent: "Asia"),
        CountryEntry(name: "Philippines", isoCode: "PH", continent: "Asia"),
        CountryEntry(name: "Qatar", isoCode: "QA", continent: "Asia"),
        CountryEntry(name: "Saudi Arabia", isoCode: "SA", continent: "Asia"),
        CountryEntry(name: "Singapore", isoCode: "SG", continent: "Asia"),
        CountryEntry(name: "South Korea", isoCode: "KR", continent: "Asia"),
        CountryEntry(name: "Sri Lanka", isoCode: "LK", continent: "Asia"),
        CountryEntry(name: "Syria", isoCode: "SY", continent: "Asia"),
        CountryEntry(name: "Taiwan", isoCode: "TW", continent: "Asia"),
        CountryEntry(name: "Tajikistan", isoCode: "TJ", continent: "Asia"),
        CountryEntry(name: "Thailand", isoCode: "TH", continent: "Asia"),
        CountryEntry(name: "Timor-Leste", isoCode: "TL", continent: "Asia"),
        CountryEntry(name: "Turkey", isoCode: "TR", continent: "Asia"),
        CountryEntry(name: "Turkmenistan", isoCode: "TM", continent: "Asia"),
        CountryEntry(name: "UAE", isoCode: "AE", continent: "Asia"),
        CountryEntry(name: "Uzbekistan", isoCode: "UZ", continent: "Asia"),
        CountryEntry(name: "Vietnam", isoCode: "VN", continent: "Asia"),
        CountryEntry(name: "Yemen", isoCode: "YE", continent: "Asia"),
        // Europe
        CountryEntry(name: "Albania", isoCode: "AL", continent: "Europe"),
        CountryEntry(name: "Andorra", isoCode: "AD", continent: "Europe"),
        CountryEntry(name: "Austria", isoCode: "AT", continent: "Europe"),
        CountryEntry(name: "Belarus", isoCode: "BY", continent: "Europe"),
        CountryEntry(name: "Belgium", isoCode: "BE", continent: "Europe"),
        CountryEntry(name: "Bosnia and Herzegovina", isoCode: "BA", continent: "Europe"),
        CountryEntry(name: "Bulgaria", isoCode: "BG", continent: "Europe"),
        CountryEntry(name: "Croatia", isoCode: "HR", continent: "Europe"),
        CountryEntry(name: "Czech Republic", isoCode: "CZ", continent: "Europe"),
        CountryEntry(name: "Denmark", isoCode: "DK", continent: "Europe"),
        CountryEntry(name: "Estonia", isoCode: "EE", continent: "Europe"),
        CountryEntry(name: "Finland", isoCode: "FI", continent: "Europe"),
        CountryEntry(name: "France", isoCode: "FR", continent: "Europe"),
        CountryEntry(name: "Germany", isoCode: "DE", continent: "Europe"),
        CountryEntry(name: "Greece", isoCode: "GR", continent: "Europe"),
        CountryEntry(name: "Hungary", isoCode: "HU", continent: "Europe"),
        CountryEntry(name: "Iceland", isoCode: "IS", continent: "Europe"),
        CountryEntry(name: "Ireland", isoCode: "IE", continent: "Europe"),
        CountryEntry(name: "Italy", isoCode: "IT", continent: "Europe"),
        CountryEntry(name: "Kosovo", isoCode: "XK", continent: "Europe"),
        CountryEntry(name: "Latvia", isoCode: "LV", continent: "Europe"),
        CountryEntry(name: "Liechtenstein", isoCode: "LI", continent: "Europe"),
        CountryEntry(name: "Lithuania", isoCode: "LT", continent: "Europe"),
        CountryEntry(name: "Luxembourg", isoCode: "LU", continent: "Europe"),
        CountryEntry(name: "Malta", isoCode: "MT", continent: "Europe"),
        CountryEntry(name: "Moldova", isoCode: "MD", continent: "Europe"),
        CountryEntry(name: "Monaco", isoCode: "MC", continent: "Europe"),
        CountryEntry(name: "Montenegro", isoCode: "ME", continent: "Europe"),
        CountryEntry(name: "Netherlands", isoCode: "NL", continent: "Europe"),
        CountryEntry(name: "North Macedonia", isoCode: "MK", continent: "Europe"),
        CountryEntry(name: "Norway", isoCode: "NO", continent: "Europe"),
        CountryEntry(name: "Poland", isoCode: "PL", continent: "Europe"),
        CountryEntry(name: "Portugal", isoCode: "PT", continent: "Europe"),
        CountryEntry(name: "Romania", isoCode: "RO", continent: "Europe"),
        CountryEntry(name: "Russia", isoCode: "RU", continent: "Europe"),
        CountryEntry(name: "San Marino", isoCode: "SM", continent: "Europe"),
        CountryEntry(name: "Serbia", isoCode: "RS", continent: "Europe"),
        CountryEntry(name: "Slovakia", isoCode: "SK", continent: "Europe"),
        CountryEntry(name: "Slovenia", isoCode: "SI", continent: "Europe"),
        CountryEntry(name: "Spain", isoCode: "ES", continent: "Europe"),
        CountryEntry(name: "Sweden", isoCode: "SE", continent: "Europe"),
        CountryEntry(name: "Switzerland", isoCode: "CH", continent: "Europe"),
        CountryEntry(name: "Ukraine", isoCode: "UA", continent: "Europe"),
        CountryEntry(name: "United Kingdom", isoCode: "GB", continent: "Europe"),
        CountryEntry(name: "Vatican City", isoCode: "VA", continent: "Europe"),
        // North America
        CountryEntry(name: "Antigua and Barbuda", isoCode: "AG", continent: "North America"),
        CountryEntry(name: "Bahamas", isoCode: "BS", continent: "North America"),
        CountryEntry(name: "Barbados", isoCode: "BB", continent: "North America"),
        CountryEntry(name: "Belize", isoCode: "BZ", continent: "North America"),
        CountryEntry(name: "Canada", isoCode: "CA", continent: "North America"),
        CountryEntry(name: "Costa Rica", isoCode: "CR", continent: "North America"),
        CountryEntry(name: "Cuba", isoCode: "CU", continent: "North America"),
        CountryEntry(name: "Dominica", isoCode: "DM", continent: "North America"),
        CountryEntry(name: "Dominican Republic", isoCode: "DO", continent: "North America"),
        CountryEntry(name: "El Salvador", isoCode: "SV", continent: "North America"),
        CountryEntry(name: "Grenada", isoCode: "GD", continent: "North America"),
        CountryEntry(name: "Guatemala", isoCode: "GT", continent: "North America"),
        CountryEntry(name: "Haiti", isoCode: "HT", continent: "North America"),
        CountryEntry(name: "Honduras", isoCode: "HN", continent: "North America"),
        CountryEntry(name: "Jamaica", isoCode: "JM", continent: "North America"),
        CountryEntry(name: "Mexico", isoCode: "MX", continent: "North America"),
        CountryEntry(name: "Nicaragua", isoCode: "NI", continent: "North America"),
        CountryEntry(name: "Panama", isoCode: "PA", continent: "North America"),
        CountryEntry(name: "Saint Kitts and Nevis", isoCode: "KN", continent: "North America"),
        CountryEntry(name: "Saint Lucia", isoCode: "LC", continent: "North America"),
        CountryEntry(name: "Saint Vincent and the Grenadines", isoCode: "VC", continent: "North America"),
        CountryEntry(name: "Trinidad and Tobago", isoCode: "TT", continent: "North America"),
        CountryEntry(name: "United States", isoCode: "US", continent: "North America"),
        // Oceania
        CountryEntry(name: "Australia", isoCode: "AU", continent: "Oceania"),
        CountryEntry(name: "Fiji", isoCode: "FJ", continent: "Oceania"),
        CountryEntry(name: "Kiribati", isoCode: "KI", continent: "Oceania"),
        CountryEntry(name: "Marshall Islands", isoCode: "MH", continent: "Oceania"),
        CountryEntry(name: "Micronesia", isoCode: "FM", continent: "Oceania"),
        CountryEntry(name: "Nauru", isoCode: "NR", continent: "Oceania"),
        CountryEntry(name: "New Zealand", isoCode: "NZ", continent: "Oceania"),
        CountryEntry(name: "Palau", isoCode: "PW", continent: "Oceania"),
        CountryEntry(name: "Papua New Guinea", isoCode: "PG", continent: "Oceania"),
        CountryEntry(name: "Samoa", isoCode: "WS", continent: "Oceania"),
        CountryEntry(name: "Solomon Islands", isoCode: "SB", continent: "Oceania"),
        CountryEntry(name: "Tonga", isoCode: "TO", continent: "Oceania"),
        CountryEntry(name: "Tuvalu", isoCode: "TV", continent: "Oceania"),
        CountryEntry(name: "Vanuatu", isoCode: "VU", continent: "Oceania"),
        // South America
        CountryEntry(name: "Argentina", isoCode: "AR", continent: "South America"),
        CountryEntry(name: "Bolivia", isoCode: "BO", continent: "South America"),
        CountryEntry(name: "Brazil", isoCode: "BR", continent: "South America"),
        CountryEntry(name: "Chile", isoCode: "CL", continent: "South America"),
        CountryEntry(name: "Colombia", isoCode: "CO", continent: "South America"),
        CountryEntry(name: "Ecuador", isoCode: "EC", continent: "South America"),
        CountryEntry(name: "Guyana", isoCode: "GY", continent: "South America"),
        CountryEntry(name: "Paraguay", isoCode: "PY", continent: "South America"),
        CountryEntry(name: "Peru", isoCode: "PE", continent: "South America"),
        CountryEntry(name: "Suriname", isoCode: "SR", continent: "South America"),
        CountryEntry(name: "Uruguay", isoCode: "UY", continent: "South America"),
        CountryEntry(name: "Venezuela", isoCode: "VE", continent: "South America"),
    ]
}
